name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version environment variable
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push app-code
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zyange/app-code:${{ env.VERSION }}
            zyange/app-code:latest
      - name: Build and push app-code-login
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./login/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zyange/app-code-login:${{ env.VERSION }}
            zyange/app-code-login:latest
      - name: Build and push app-code-account
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./account/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zyange/app-code-account:${{ env.VERSION }}
            zyange/app-code-account:latest
      - name: Build and push app-code-loans
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./loans/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zyange/app-code-loans:${{ env.VERSION }}
            zyange/app-code-loans:latest
